[
  ../modules/brave
  ../modules/git
  ../modules/i3
  ../modules/kitty
  ../modules/qutebrowser
  ../modules/rofi
  ../modules/spotify
  ../modules/sxhkd
  ../modules/vim
  ../modules/xidlehook
  ../modules/zathura
  ../modules/zsh
  ../modules/rofi_screenshot
]
