{ config, lib, pkgs, ... }:

let
  cfg = config.homebrew;
  isDarwin = pkgs.stdenv.hostPlatform.isDarwin;
  
  brewPrefix =
    if pkgs.stdenv.hostPlatform.isAarch64
    then "/opt/homebrew"
    else "/usr/local";
  
  brewBin = "${brewPrefix}/bin/brew";
  brewfilePath = "${config.xdg.configHome}/brew/Brewfile";
  
  render = {
    taps ? [],
    brews ? [],
    casks ? [],
    masApps ? [],
    extraLines ? ""
  }:
    ''
      # Generated by Home Manager from Nix lists.
      # Edit your `homebrew.*` options, not this file.
      
      ${lib.concatStringsSep "\n" (map (t: "tap \"${t}\"") taps)}
      
      ${lib.concatStringsSep "\n" (map (p: "brew \"${p}\"") brews)}
      
      ${lib.concatStringsSep "\n" (map (c: "cask \"${c}\"") casks)}
      
      ${lib.concatStringsSep "\n" (map (a: "mas \"${a.name}\", id: ${toString a.id}") masApps)}
      
      ${extraLines}
    '';
in
{
  options.homebrew = {
    enable = lib.mkEnableOption "Homebrew bootstrap + Brewfile generation (HM-only, macOS)";
    
    taps = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      example = [ "homebrew/cask-fonts" ];
      description = "Homebrew taps to include in the generated Brewfile.";
    };
  
    brews = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      example = [ "ripgrep" "fd" ];
      description = "Homebrew formulae (CLI/tools/libs) to include in the Brewfile.";
    };
  
    casks = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      example = [ "kitty" "amethyst" ];
      description = "Homebrew casks (GUI apps) to include in the Brewfile.";
    };
  
    masApps = lib.mkOption {
      type = lib.types.listOf (lib.types.submodule {
      options = {
          name = lib.mkOption { type = lib.types.str; };
          id = lib.mkOption { type = lib.types.int; };
        };
      });
      default = [];
      example = [ { name = "Xcode"; id = 497799835; } ];
      description = "Mac App Store apps for Brewfile (requires `mas` and App Store login).";
    };
  
    extraBrewfileLines = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra raw Brewfile lines appended to the generated Brewfile.";
    };
  
    autoBundleOnSwitch = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "If true, run `brew bundle` automatically on each `home-manager switch`.";
    };
  };
  
  config = lib.mkIf (cfg.enable && isDarwin) {
  # Generate Brewfile
  xdg.configFile."brew/Brewfile".text = render {
    taps = cfg.taps;
    brews = cfg.brews;
    casks = cfg.casks;
    masApps = cfg.masApps;
    extraLines = cfg.extraBrewfileLines;
  };
  
  # Bootstrap Homebrew if missing
  home.activation.installHomebrew =
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      set -euo pipefail
      if [ ! -x "${brewBin}" ]; then
      echo "Homebrew not found at ${brewBin}. Installing..."
      NONINTERACTIVE=1 /bin/bash -c "$(
      /usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
      )"
      else
      echo "Homebrew already installed."
      fi
    '';
  
  # Make brew available in interactive shells (handy on fresh machines)
  home.sessionPath = [ "${brewPrefix}/bin" "${brewPrefix}/sbin" ];
  
  # Alias for convenience
  home.shellAliases."brew-sync" =
    "${brewBin} bundle --file ${lib.escapeShellArg brewfilePath}";
  
  # Also provide a command so it works even without shell alias reload
  home.packages = [
    (pkgs.writeShellScriptBin "brew-sync" ''
      exec "${brewBin}" bundle --file "${brewfilePath}"
    '')
  ];
  
  # Optional: run brew bundle automatically on switch
  home.activation.brewBundle = lib.mkIf cfg.autoBundleOnSwitch
    (lib.hm.dag.entryAfter [ "installHomebrew" ] ''
      set -euo pipefail
      echo "Running brew bundle..."
      "${brewBin}" bundle --file "${brewfilePath}"
    '');
  };
}
